// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import SubmitSpinnerController from "./submit_spinner_controller";
application.register("submit-spinner", SubmitSpinnerController);

import DialogController from "./dialog_controller";
application.register("dialog", DialogController);

import MobileMenuController from "./mobile_menu_controller";
application.register("mobile-menu", MobileMenuController);
